### ISSUE TITLE
Game crashes on attempt to join a coop lobby

### ISSUE THREAD

**Issue by Patschke** [Tempus/Slay-the-Spire-Together#1]
On attempt to join a game it crashes. I can click coop and can see the list on the right. Sometimes I am able to join the screen where I am supposed to click ready, sometimes I can't. The game just crashes after a short time. 

Two example logs are attached: 

[SlayTheSpire_202102142041_1.log.zip](https://github.com/Tempus/Slay-the-Spire-Together/files/5978482/SlayTheSpire_202102142041_1.log.zip)
[SlayTheSpire_202102142039_1.log.zip](https://github.com/Tempus/Slay-the-Spire-Together/files/5978483/SlayTheSpire_202102142039_1.log.zip)

**Comment by yanpiaowanli** [comment]
the same problem. Two of my friends and I played together, but only one of us could join the game correctly. We have tried to restart the computer for a few times, but it did not work.

**Comment by Tempus** [comment]
I believe this is a bug with people playing from a save file that doesn't have ascension mode unlocked, can you confirm?

**Comment by Patschke** [comment]
I do have ascension mode unlocked, and was able to host a game and join the versus game later. I expected that I just noticed the bug you experienced yourself a little later, but had it for some reason occurring a few times in a row earlier? I can't answer for @yanpiaowanli  though.

**Comment by yanpiaowanli** [comment]
> 
> 
> I believe this is a bug with people playing from a save file that doesn't have ascension mode unlocked, can you confirm?

We do have ascension mode unlocked, and the game we played was ascension mode level 0, with neow's bonus and heart run on. Maybe the crash is caused by a standard run that hadn't been finished (Only a possibility, I'm not sure about that. But after I quit my last run, I could join the coop game.)

**Comment by Tempus** [comment]
Okay, fixed a variety of possible bugs this could be, and put in some safety measures. Hopefully no crashes next update cross my fingers!
