### ISSUE TITLE
Skipped Act 3

### ISSUE THREAD

**Issue by LocasMaxis** [Tempus/Slay-the-Spire-Together#2]
Was playing a co-op game with my boyfriend, him as Defect and me as Silent. And after we selected act 2's team relic we both started act three and clicking the boss tile on the map instant warped us to the boss. I can post run histories if it might be related to our gear.

**Comment by LocasMaxis** [comment]
Can confirm it happened again, after I crashed on selecting an empty room card reward with the Dowsing Rod the game just crashed to desktop. But my boyfriend carried on and defeated the act 2 boss and tried clicking the act 3 boss from the start again and instant started the battle.

**Comment by Tempus** [comment]
This is fixed, new version coming soon, thanks for the report!
