### ISSUE TITLE
Singing Bowl Bug

### ISSUE THREAD

**Issue by KhaloftheWild** [Tempus/Slay-the-Spire-Together#21]
Sending singing bowl to a player that already has it skyrockets the receiving player's hp to infinity when that player enters a card reward screen.

**Comment by Sasurai087** [comment]
I can confirm the same thing happening to me as well. Staying on the reward screen increases max HP by an extremely fast rate. My HP was 14,500 by the time I beat the second boss.

**Comment by Tempus** [comment]
Fixed in 1.6 (out now), thanks for the report!
