### ISSUE TITLE
Dimensioneel bug if player has < 3 non-boss relics

### ISSUE THREAD

**Issue by emilyzhong** [Tempus/Slay-the-Spire-Together#22]
I ran into a bug where my player had less than 3 non-boss relics.

This made it difficult to proceed to the next stage, and when I was (via clicking around randomly), the relic selection visuals remained on the page. See attached screenshot.
![image](https://user-images.githubusercontent.com/23442055/115983698-99712900-a557-11eb-9347-bfc059fddd7e.png)

**Comment by rhaskett** [comment]
I ran into this bug as well.  I had two non-boss relics after an rough act 1.

**Comment by Autoquark** [comment]
I have also experienced this.

**Comment by silastsui** [comment]
I also ran into this. I think this bug can be pretty common once you're on higher ascension levels. Those elites really hurt...

**Comment by Tempus** [comment]
Fixed in 1.6 (out now), thanks for the report!
