### ISSUE TITLE
Mark of the Bloom and shared health bug

### ISSUE THREAD

**Issue by noahjshirk** [Tempus/Slay-the-Spire-Together#23]
We took the shared health pool boss relic, then I took the Mark of the Bloom event relic. In the heart fight, I took fatal damage, but we had a String of Fate life remaining. Rather than returning to full, reduced health, we both had our life bars disappear and the cards were unplayable. 

Thanks for the mod, we are having so much fun.

**Comment by Tempus** [comment]
Duplicate issue of #20 , haven't fixed it yet, sorry for the trouble.
