### ISSUE TITLE
Message in a Bottle softlock

### ISSUE THREAD

**Issue by belguawhale** [Tempus/Slay-the-Spire-Together#24]
I was playing Ironclad and sent a Metallicize to my friend playing Silent, who sent Eviscerate back to me using the Message in a Bottle team relic. My friend got the Metallicize and was able to continue, however the Eviscerate did not make it into my deck and the Proceed button was stuck, unable to continue. Log attached.

A possible place to look for reproing is having the deck interface open when the other player selects Message in a Bottle, causing the card swap interface to appear above the deck interface.

Logs below when I tried to click Proceed:

![image](https://user-images.githubusercontent.com/14934900/116189748-6c5b7c80-a6f7-11eb-9d52-b851eaf46d31.png)

**Comment by Tempus** [comment]
Fixed in 1.6 (out now), thanks for the report!
