### ISSUE TITLE
The Act 3 skip to final boss in coop still works

### ISSUE THREAD

**Issue by LocasMaxis** [Tempus/Slay-the-Spire-Together#3]
Like the title says, the act three boss is still able to be jumped to from the start of act 3. It's only act three and it might still be happening only with the Ladder relic as we had that at the end of act 2, but I can't be sure as I really don't want to keep trying in the middle of runs. Still the update has been a lot more stable so keep up the good work!

**Comment by Tempus** [comment]
Hey, can you confirm you're on 1.2? Steam has had a lot of troubles pushing out the new update.

**Comment by LocasMaxis** [comment]
https://i.gyazo.com/0a3ee74e66685ebe1a0f3e2699ffc712.png
Here's a screen cap from the mod loader.

**Comment by Tempus** [comment]
Thank you! I'll try to figure this one out again

**Comment by Tempus** [comment]
Still haven't been able to repro this despite much effort, unlikely to be fixed in the short term, sorry for the trouble.

**Comment by Tempus** [comment]
I have implemented several fixes for this now, but am unable to test. Closing this issue, if it reoccurs in 1.4, please re-report!
