### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by fallsister** [Tempus/Slay-the-Spire-Together#7]
The game crashes after starting the game
![QQ图片20210226142737](https://user-images.githubusercontent.com/79685591/109263796-dadaa600-783e-11eb-8cbd-582a5cbdd623.png)
![QQ图片20210226142754](https://user-images.githubusercontent.com/79685591/109263808-e0d08700-783e-11eb-80ec-32f5a815bec8.png)

**Comment by Tempus** [comment]
Thanks for the report, this should be fixed next update
