### ISSUE TITLE
Not working with mods that add new beginning choices

### ISSUE THREAD

**Issue by HeartyYF** [Tempus/Slay-the-Spire-Together#9]
For example, this mod: [Lobotomy Corp.](https://steamcommunity.com/sharedfiles/filedetails/?id=1969477416)
To play contents from this mod, you need to get a special relic at the beginning, but I found that choice is missing.

**Comment by Tempus** [comment]
Sorry, this feature is out of scope. If you want me to specifically fix Lobotomy corp compatibility, you can throw down for the 25$ Patreon. Otherwise, I will not be implementing this. Sorry for the trouble!
